# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-07-19 11:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_user_botactived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('description', models.CharField(max_length=450)),
            ],
        ),
    ]
