# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-07-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_multipolygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipolygon',
            name='name',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
