# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-07-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20170719_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipolygon',
            name='price',
            field=models.CharField(default='price', max_length=450),
        ),
        migrations.AlterField(
            model_name='multipolygon',
            name='description',
            field=models.CharField(default='description', max_length=450),
        ),
    ]
