# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-08-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20170719_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='price', max_length=450)),
                ('maxHours', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=250)),
                ('days', models.CharField(max_length=250)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Parking')),
            ],
        ),
        migrations.RemoveField(
            model_name='multipolygon',
            name='price',
        ),
        migrations.AddField(
            model_name='parking',
            name='multi_polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.MultiPolygon'),
        ),
    ]
