# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-08-09 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20170809_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parking',
            new_name='ParkingZone',
        ),
    ]
